---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: generate-ssh-keys-simple-taskrun
spec:
  serviceAccountName: generate-ssh-keys-task
  taskRef:
    kind: Task
    name: generate-ssh-keys
  params: []
