---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: execute-in-vm-with-ssh-taskrun
spec:
  serviceAccountName: execute-in-vm-task
  taskRef:
    kind: Task
    name: execute-in-vm
  params:
    - name: vmName
      value: vm-example
    - name: secretName
      value: ssh-secret
    - name: command
      value:
        - systemctl
    - name: args
      value:
        - 'start'
        - 'postgresql.service'
