---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/deprecated: "true"
    sourceTemplateName.params.task.kubevirt.io/kind: Template
    sourceTemplateName.params.task.kubevirt.io/apiVersion: template.openshift.io/v1
    sourceTemplateNamespace.params.task.kubevirt.io/type: namespace
    targetTemplateName.params.task.kubevirt.io/kind: Template
    targetTemplateName.params.task.kubevirt.io/apiVersion: template.openshift.io/v1
    targetTemplateNamespace.params.task.kubevirt.io/type: namespace
    allowReplace.params.task.kubevirt.io/type: boolean
  labels:
    task.kubevirt.io/type: copy-template
    task.kubevirt.io/category: copy-template
  name: copy-template
spec:
  params:
    - name: sourceTemplateName
      description: Name of an OpenShift template to copy template from.
      type: string
    - name: sourceTemplateNamespace
      description: Namespace of an source OpenShift template to copy template from. (defaults to active namespace)
      type: string
      default: ""
    - name: targetTemplateName
      description: Name of an target OpenShift template.
      type: string
      default: ""
    - name: targetTemplateNamespace
      description: Namespace of an target OpenShift template to create in. (defaults to active namespace)
      type: string
      default: ""
    - name: allowReplace
      description: Allow replacing already existing template (same combination name/namespace). Allowed values true/false
      type: string
      default: "false"
  results:
    - name: name
      description: The name of a template that was created.
    - name: namespace
      description: The namespace of a template that was created.
  steps:
    - name: copytemplate
      image: "quay.io/kubevirt/tekton-tasks:v0.17.0"
      command:
        - copy-template
      args:
        - "--output=yaml"
      env:
        - name: SOURCE_TEMPLATE_NAME
          value: $(params.sourceTemplateName)
        - name: SOURCE_TEMPLATE_NAMESPACE
          value: $(params.sourceTemplateNamespace)
        - name: TARGET_TEMPLATE_NAME
          value: $(params.targetTemplateName)
        - name: TARGET_TEMPLATE_NAMESPACE
          value: $(params.targetTemplateNamespace)
        - name: ALLOW_REPLACE
          value: $(params.allowReplace)
