---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    task.kubevirt.io/associatedServiceAccount: execute-in-vm-task
    vmNamespace.params.task.kubevirt.io/type: namespace
    secretName.params.task.kubevirt.io/type: execute-in-vm-secret
    script.params.task.kubevirt.io/type: script
  labels:
    task.kubevirt.io/type: execute-in-vm
    task.kubevirt.io/category: execute-in-vm
  name: execute-in-vm
spec:
  params:
    - description: Name of a VM to execute the action in
      name: vmName
      type: string
    - description: Namespace of a VM to execute the action in (defaults to active namespace)
      name: vmNamespace
      type: string
      default: ""
    - description: Secret to use when connecting to a VM
      name: secretName
      type: string
      default: "__empty__"
    - description: Command to execute in a VM
      name: command
      type: array
      default: []
    - description: Arguments of a command
      name: args
      type: array
      default: []
    - description: Script to execute in a VM
      name: script
      type: string
      default: ""
  steps:
    - name: execute-in-vm
      image: quay.io/kubevirt/execute-in-vm:v0.0.1
      command:
        - entrypoint
      args:
        - '--vm-name'
        - $(params.vmName)
        - '--vm-namespace'
        - $(params.vmNamespace)
        - '--'
        - $(params.command)
        - $(params.args)
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EXECUTE_SCRIPT
          value: $(params.script)
      volumeMounts:
        - mountPath: /data/connectionsecret/
          name: connectionsecret
  volumes:
    - name: connectionsecret
      secret:
        secretName: $(params.secretName)
        optional: true
