apiVersion: v1
kind: Secret
metadata:
  name: disk-virt-sysprep-taskrun-workspace
type: Opaque
stringData:
  password: mysecretpassword
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: disk-virt-sysprep-taskrun-workspace
spec:
  taskRef:
    kind: Task
    name: disk-virt-sysprep
  params:
    - name: pvc
      value: example-pvc
    - name: sysprepCommands
      value: |
        update
        install make,ansible
        operations firewall-rules,defaults
        root-password file:/data/password
  workspaces:
    - name: data
      secret:
        name: disk-virt-sysprep-taskrun-workspace
