---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-dv-from-manifest-taskrun
spec:
  serviceAccountName: create-datavolume-task
  taskRef:
    kind: ClusterTask
    name: create-datavolume-from-manifest
  params:
    - name: waitForSuccess
      value: 'true'
    - name: manifest
      value: |
        apiVersion: cdi.kubevirt.io/v1beta1
        kind: DataVolume
        metadata:
          generateName: example-dv-
        spec:
          pvc:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
            volumeMode: Filesystem
          source:
            blank: {}
